ExamplePaymentPlugin/Models/EPPModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web.Mvc;
using static ExamplePaymentPlugin.EPProvider;

namespace ExamplePaymentPlugin.Models
{
    public class ConfigModel
    {
        public ConfigModel()
        {
            UseDebugMode = false;
            UseAuthCapture = false;
            ExecutionMode = GatewayExecutionMode.AlwaysAccept;
            PaymentMethods = new List<PaymentMethodModel>();
        }

        public int? GatewayId { get; set; }
        
        public bool UseDebugMode { get; set; }
        
        public bool UseAuthCapture { get; set; }
        
        public GatewayExecutionMode ExecutionMode { get; set; }

        public List<SelectListItem> ExecutionModes { get; set; }

        public List<PaymentMethodModel> PaymentMethods { get; set; }

        public string AssemblyInfo { get; set; }

        public string SaveOnly { get; set; }

        public bool ShowConfirmationMessage { get; set; }
    }

    public class PaymentMethodModel
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public bool IsSelected { get; set; }
    }

    public class ExamplePaymentButtonModel
    {
        public int OrderId { get; set; }

        public int OrderNumber { get; set; }


        public decimal Amount { get; set; }
    }
}

ExamplePaymentPlugin/Controllers/EPPAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web.Mvc;
using CommerceBuilder.Common;
using ExamplePaymentPlugin.Models;
using CommerceBuilder.Utility;
using CommerceBuilder.Web.Mvc;
using CommerceBuilder.Payments;
using CommerceBuilder.Payments.Providers;

namespace ExamplePaymentPlugin.Controllers
{
    public class EPPAdminController : AbleAdminController
    {
        private readonly IPaymentGatewayRepository _gatewayRepo;
        private readonly IPaymentMethodRepository _methodRepo;

        private readonly PaymentInstrumentType[] _hiddenMethods = { PaymentInstrumentType.GiftCertificate, PaymentInstrumentType.GoogleCheckout, PaymentInstrumentType.Mail, PaymentInstrumentType.PhoneCall, PaymentInstrumentType.PurchaseOrder, PaymentInstrumentType.PayPal };

        public EPPAdminController(IPaymentGatewayRepository gatewayRepo, IPaymentMethodRepository methodRepo)
        {
            _gatewayRepo = gatewayRepo;
            _methodRepo = methodRepo;
        }

        public ActionResult Config(int? id)
        {
            int gatewayId = id ?? 0;
            PaymentGateway gateway = _gatewayRepo.Load(gatewayId);

            var aName = GetType().Assembly.GetName();
            string assemblyInfo = aName.Name.ToString() + "&nbsp;(v" + aName.Version.ToString() + ")";

            var model = new ConfigModel();
            model.AssemblyInfo = assemblyInfo;
            model.ExecutionModes = Enum.GetNames(typeof(EPProvider.GatewayExecutionMode))
                .Select(name => new SelectListItem() { Text = name, Value = name })
                .ToList();
            model.PaymentMethods = _methodRepo.LoadPaymentMethods(_hiddenMethods).Select(method => new PaymentMethodModel()
            {
                Id = method.Id,
                Name = method.Name }
            ).ToList();

            if (gateway != null)
            {
                model.GatewayId = gateway.Id;
                model.PaymentMethods.ForEach(method => method.IsSelected = gateway.PaymentMethods.Any(pm => pm.Id == method.Id));

                var configurationData = gateway.ParseConfigData();
                if (configurationData.ContainsKey("UseDebugMode"))
                    model.UseDebugMode = AlwaysConvert.ToBool(configurationData["UseDebugMode"], false);
                if (configurationData.ContainsKey("ExecutionMode"))
                    model.ExecutionMode = AlwaysConvert.ToEnum<EPProvider.GatewayExecutionMode>(configurationData["ExecutionMode"], EPProvider.GatewayExecutionMode.AlwaysAccept);
                if (configurationData.ContainsKey("UseAuthCapture"))
                    model.UseAuthCapture = AlwaysConvert.ToBool(configurationData["UseAuthCapture"], true);
            }

            return View("~/Plugins/ExamplePaymentPlugin/Views/Config.cshtml", model);
        }

        [HttpPost]
        [ValidateAjax]
        public ActionResult Config(ConfigModel model, FormCollection form)
        {
            var paymentMethods = _methodRepo.LoadPaymentMethods(_hiddenMethods);
            PaymentGateway gateway = model.GatewayId.HasValue ? _gatewayRepo.Load(model.GatewayId.Value) : null;
            model.ShowConfirmationMessage = true;
            if (gateway == null)
            {
                string classId = Misc.GetClassId(typeof(EPProvider));
                var provider = Activator.CreateInstance(Type.GetType(classId)) as IPaymentProvider;
                gateway = new PaymentGateway();
                gateway.ClassId = classId;
                gateway.Name = provider.Name;
                gateway.Store = AbleContext.Current.Store;
                model.ShowConfirmationMessage = false;
            }

            Dictionary<string, string> configData = new Dictionary<string, string>();
            configData.Add("UseDebugMode", model.UseDebugMode.ToString());
            configData.Add("ExecutionMode", model.ExecutionMode.ToString());
            configData.Add("UseAuthCapture", model.UseAuthCapture.ToString());
            gateway.UpdateConfigData(configData);
            _gatewayRepo.Save(gateway);

            //UPDATE PAYMENT METHODS

            var selectedKeys = form.AllKeys.Where(key => key.ToUpper().StartsWith("METHOD_CHK_",
                  StringComparison.InvariantCultureIgnoreCase)).ToList();

            foreach (var key in selectedKeys)
            {
                int paymentMethodId = AlwaysConvert.ToInt(key.Substring(11));
                PaymentMethod method = paymentMethods.Where(m => m.Id == paymentMethodId).FirstOrDefault();
                if (method != null)
                {
                    if (form[key].Contains("true"))
                    {
                        method.PaymentGateway = gateway;
                    }
                    else if (method.PaymentGateway != null && method.PaymentGateway.Id == gateway.Id)
                    {
                        method.PaymentGateway = null;
                    }

                    _methodRepo.Save(method);
                }
            }

            if (model.SaveOnly.Equals("true"))
            {
                return Json(new { status = "Success", Id = gateway.Id, showMessage = model.ShowConfirmationMessage });
            }
            else
            {
                return Json(new { status = "Redirect", Url = Url.Action("Gateways", "Payments") });
            }
        }
    }
}

ExamplePaymentPlugin/Controllers/EPPRetailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web.Mvc;
using CommerceBuilder.Web;
using CommerceBuilder.Web.Mvc;
using ExamplePaymentPlugin.Models;

namespace ExamplePaymentPlugin.Controllers
{
    public class EPPRetailController : AbleController
    {
        [RegisterWidget]
        public ActionResult ExamplePaymentButton()
        {
            var model = new ExamplePaymentButtonModel() { OrderId = 123, Amount = 10 };
            return PartialView("~/Plugins/ExamplePaymentPlugin/Views/Retail/_ExamplePaymentButton.cshtml", model);
        }
    }
}

ExamplePaymentPlugin/Views/Config.cshtml
@model ConfigModel
@{
    ViewBag.PageCaption = "Example Payment Plugin";
    ViewBag.Title = "Example Payment Plugin";
}

@using (Ajax.BeginForm("Config", "EPPAdmin", new AjaxOptions() { OnSuccess = "GatewayAdded" }))
{
    @Html.HiddenFor(m =>m.GatewayId)
    @Html.HiddenFor(m => m.SaveOnly)
    <div class="wrapper wrapper-content">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>@(Model.GatewayId.HasValue ? "Configure Example Payment Provider" : "Add Example Payment Provider")</h5>
            </div>
            <div class="ibox-content">
                <div class="content">
                    <div class="well">
                        <p>This is not a real payment gateway. Only use the AbleCommerce gateway for testing purposes.</p>
                    </div>
                    <div class="row">
                        <div class="col-lg-6 b-r">
                            <div class="form-group">
                                <label data-content="The integration assembly name and version." class="tooltip-label">Assembly:</label>
                                <span>@Html.Raw(Model.AssemblyInfo)</span>
                            </div>
                            <div class="form-group">
                                <label data-content="Use this setting to force a successful or failed transaction test." class="tooltip-label">Execution Mode</label>
                                @Html.DropDownListFor(m => m.ExecutionMode, Model.ExecutionModes, new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group" id="Config_UseAuthCapture">
                                <label data-content="Use 'Authorize' to request authorization without capturing funds at the time of purchase. You can capture authorized transactions through the order admin interface. Use 'Sale' to capture funds immediately at the time of purchase." class="tooltip-label">Authorization Mode</label>
                                <div class="radio radio-success">
                                    @Html.RadioButtonFor(m => m.UseAuthCapture, false)
                                    <label for="Config_UseAuthCapture_0">Authorize (recommended)</label>
                                </div>
                                <div class="radio radio-success">
                                    @Html.RadioButtonFor(m => m.UseAuthCapture, true)
                                    <label for="Config_UseAuthCapture_1">Authorize &amp; Capture</label>
                                </div>
                            </div>
                        </div>
                    </div>
                    @if (Model.PaymentMethods.Count > 0)
                    {
                        <div class="hr-line-dashed"></div>
                        <label data-content="Select all the payment methods that apply to this payment service." class="tooltip-label">Payment Methods</label>
                        foreach (var method in Model.PaymentMethods)
                        {
                            <div class="checkbox checkbox-success">
                                @Html.CheckBox("METHOD_CHK_" + method.Id, method.IsSelected)
                                <label for="METHOD_CHK_"@method.Id>
                                    @method.Name
                                </label>
                            </div>
                        }
                    }
                </div>
            </div>
        </div>
    </div>
    <br /><br /><br />
    <div class="sticky-footer">
        <div class="pull-left">
            <a href="@Url.Action("Gateways", "Payments")" class="btn btn-default">Cancel</a>
        </div>
        <div class="pull-right">
            @{ var btnText = Model.GatewayId == null || Model.GatewayId == 0 ? "Save and Edit" : "Save"; }
            <button type="submit" id="save" class="btn btn-primary">@btnText</button>
            <button type="submit" id="saveAndClose" class="btn btn-primary">Save and Close</button>
        </div>
    </div>

                }

@section Scripts {
    <script type="text/javascript">
        $(document).ready(function () {

            $('#save').click(function () {
                $('#SaveOnly').val("true");
            });

            $('#saveAndClose').click(function () {
                $('#SaveOnly').val("false");
            });
        });

        function GatewayAdded(data)
        {
            if(data.status == "Redirect")
            {
                window.location = data.Url;
            }
            else if (data.status == "Success")
            {
                $('#Id').val(data.Id);
                if (data.showMessage)
                {
                    toastr.success("Gateway updated successfully", "Success");
                }
                else
                {
                    window.location.href = "@Url.Action("Config")" + "?id=" + data.Id;
                }
            }
        }
    </script>
}

ExamplePaymentPlugin/Views/Retail/_ExamplePaymentButton.cshtml
@model ExamplePaymentButtonModel
@{ 
    // USE ORDER INFORMATION TO BUILD THE BUTTON AS PER PROVIDER DOCUMENTATION
    int orderId = Model.OrderId;
    decimal amount = Model.Amount;
}
<input name="ExamplePaymentButton" type="image" src="@Url.Content("~/Plugins/ExamplePaymentPlugin/Content/paynow.png")" alt="Pay Now" />