RandomQuotesPlugin/Models/RQPModels.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using CommerceBuilder.Web;

namespace RandomQuotesPlugin.Models
{
    public class QuoteModel
    {
        public int Id { get; set; }

        public int CreatedById { get; set; }

        public string CreatedByName { get; set; }
        
        [Required]
        public string Author { get; set; }

        [Required]
        public string Website { get; set; }

        [Required]
        public string Content { get; set; }

        public DateTime CreatedDate { get; set; }
    }

    public class RandomQuotesBoxParams : WidgetParams
    {
        public RandomQuotesBoxParams()
        {
            Caption = "Random Quote";
            ShowWebsiteLink = true;
        }
        
        [DisplayName("Caption")]
        [DefaultValue("Random Quote")]
        [Description("Allows you to change random quotes box caption if you have enabled to show caption")]
        public string Caption { get; set; }
        
        [DisplayName("Show Website Link")]
        [DefaultValue(true)]
        [Description("Allows you show website link or not if present for a quote")]
        public bool ShowWebsiteLink { get; set; }
    }
}

RandomQuotesPlugin/Controllers/RQPAdminController.cs
using System.Web.Mvc;
namespace RandomQuotesPlugin.Controllers
{
    using System.Linq;
    using CommerceBuilder.Common;
    using CommerceBuilder.Utility;
    using CommerceBuilder.Web.Mvc;
    using Models;
    
    public class RQPAdminController : AbleAdminController
    {
        private readonly IQuoteRepository _quoteRepo;

        public RQPAdminController(IQuoteRepository quoteRepo)
        {
            _quoteRepo = quoteRepo;
        }

        public ActionResult Index(string sortExpression = "CreatedDate DESC", int page = 1, int pageSize = 20)
        {
            int pageIndex = page - 1;
            int count = _quoteRepo.CountAll();

            if (pageSize == 0 && count != 0) pageSize = count;
            if (count == 0) pageSize = 20;

            var quotes = _quoteRepo.LoadAll(sortExpression, pageSize, pageIndex)
                .Select(quote => new QuoteModel()
                {
                    Id = quote.Id,
                    CreatedById = quote.CreatedBy != null ? quote.CreatedBy.Id : 0,
                    CreatedByName = quote.CreatedBy != null ? quote.CreatedBy.UserName : string.Empty,
                    Author = quote.Author,
                    Website = quote.Website,
                    Content = quote.Content,
                    CreatedDate = quote.CreatedDate
                }).ToList();

            var model = quotes; //new StaticPagedList<QuoteModel>(quotes, page, pageSize, count);

            return View("~/Plugins/RandomQuotesPlugin/Views/Index.cshtml", model);
        }

        public ActionResult AddEditQuote(int? quoteId)
        {
            Quote quote = null;
            if (quoteId.HasValue && quoteId.Value > 0)
            {
                quote = _quoteRepo.Load(quoteId.Value);
                if (quote == null)
                    return RedirectToAction("Index");
            }

            QuoteModel model = new QuoteModel();
            if (quote != null)
            {
                model.Id = quote.Id;
                model.Author = quote.Author;
                model.Website = quote.Website;
                model.Content = quote.Content;
            }

            return View("~/Plugins/RandomQuotesPlugin/Views/AddEditQuote.cshtml", model);
        }

        [HttpPost]
        public ActionResult AddEditQuote(QuoteModel model, bool saveOnly)
        {
            if (ModelState.IsValid)
            {
                Quote quote = null;
                if (model.Id > 0)
                {
                    quote = _quoteRepo.Load(model.Id);
                    if (quote == null)
                        return RedirectToAction("Index");
                }
                else
                {
                    quote = new Quote();
                }

                if (quote != null)
                {
                    quote.Author = model.Author;
                    quote.Content = model.Content;
                    quote.Website = model.Website;

                    if (quote.Id == 0)
                    {
                        quote.CreatedBy = AbleContext.Current.User;
                        quote.CreatedDate = LocaleHelper.LocalNow;
                    }

                    _quoteRepo.Save(quote);

                    if (saveOnly)
                        return RedirectToAction("AddEditQuote", new { quoteId = quote.Id });
                    else
                        return RedirectToAction("Index");
                }
            }

            return View("~/Plugins/RandomQuotesPlugin/Views/AddEditQuote.cshtml", model);
        }


        public ActionResult DeleteQuote(int quoteId)
        {
            var quote = _quoteRepo.Load(quoteId);
            if (quote != null)
                _quoteRepo.Delete(quote);
            return RedirectToAction("Index");
        }
    }
}

RandomQuotesPlugin/Controllers/RQPRetailController.cs
using System.Web.Mvc;
namespace RandomQuotesPlugin.Controllers
{
    using CommerceBuilder.Web;
    using CommerceBuilder.Web.Mvc;
    using Models;

    public class EPPRetailController : AbleController
    {
        private readonly IQuoteRepository _quoteRepo;

        public EPPRetailController(IQuoteRepository quoteRepo)
        {
            _quoteRepo = quoteRepo;
        }

        [RegisterWidget(Category = CommerceBuilder.CMS.WidgetCategory.Sidebar, DisplayName = "Random Quotes Box")]
        public ActionResult RandomQuotesBox(RandomQuotesBoxParams parameters)
        {
            var quote = _quoteRepo.GetRandomQuote();
            QuoteModel model = null;
            if (quote != null)
            {
                model = new QuoteModel()
                {
                    Id = quote.Id,
                    CreatedById = quote.CreatedBy != null ? quote.CreatedBy.Id : 0,
                    CreatedByName = quote.CreatedBy != null ? quote.CreatedBy.UserName : string.Empty,
                    Author = quote.Author,
                    Content = quote.Content,
                    Website = quote.Website,
                    CreatedDate = quote.CreatedDate
                };
            }

            ViewBag.Caption = parameters.Caption;
            ViewBag.ShowWebsiteLink = parameters.ShowWebsiteLink;

            return PartialView("~/Plugins/RandomQuotesPlugin/Views/Retail/_RandomQuotesBox.cshtml", model);
        }
    }
}

RandomQuotesPlugin/Views/AddEditQuote.cshtml
@model QuoteModel
@{
    string title = Model.Id == 0 ? "Add Quote" : "Edit Quote";
    ViewBag.PageCaption = title;
    ViewBag.Title = title;
}

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="ibox float-e-margins">
        <div class="ibox-title">
            <h5>@title</h5>
        </div>
        <div class="ibox-content">
            @using (Html.BeginForm("AddEditQuote", "RQPAdmin", null, FormMethod.Post, new { id = "quote-form" }))
            {
                @Html.Hidden("SaveOnly")
                @Html.HiddenFor(m => m.Id)
                <div class="row">
                    <div class="col-sm-12">
                        <div class="form-group">
                            <label>Author</label>
                            <div class="required-field-block">
                                @Html.TextBoxFor(m => m.Author, new { @class = "form-control" })
                                <div class="required-icon">
                                    <div class="text">*</div>
                                </div>
                                @Html.ValidationMessageFor(m => m.Author)
                            </div>
                        </div>
                        <div class="form-group">
                            <label>Website</label>
                            @Html.TextBoxFor(m => m.Website, new { @class = "form-control" })
                        </div>
                        <div class="form-group">
                            <label>Content</label>
                            <div class="required-field-block">
                                @Html.TextAreaFor(m => m.Content, new { @class = "form-control" })
                                <div class="required-icon">
                                    <div class="text">*</div>
                                </div>
                                @Html.ValidationMessageFor(m => m.Content)
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

<div class="sticky-footer">
    <div class="pull-left">
        <a id="CancelBtn" href="@Url.Action("Index", "RQPAdmin")" class="btn btn-default">Cancel</a>
    </div>
    <div class="pull-right">
        <button type="submit" id="save" class="btn btn-primary">Save</button>
        <button type="submit" id="saveAndClose" class="btn btn-primary">Save and Close</button>
    </div>
</div>

@section Scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            $('#save').click(function () {
                $('#SaveOnly').val("true");
                $('#quote-form').submit();
            });

            $('#saveAndClose').click(function () {
                $('#SaveOnly').val("false");
                $('#quote-form').submit();
            });
        });
    </script>   
}

RandomQuotesPlugin/Views/Index.cshtml
@model IList<QuoteModel>
@{
    ViewBag.PageCaption = "Random Quotes";
    ViewBag.Title = "Random Quotes";
}

@section TitleActions {

    <a class="btn btn-primary" href="@Url.Action("AddEditQuote", "RQPAdmin")">Add</a>
}

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="ibox float-e-margins">
        <div class="ibox-title">
            <h5>List of Quotes</h5>
        </div>
        <div class="ibox-content">
            @if (Model.Count > 0)
            {
                <table class="table table-stripped footable">
                    <thead>
                        <tr>
                            <th>Author</th>
                            <th>Content</th>
                            <th>Created At</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (QuoteModel quote in Model)
                        {
                            <tr>
                                <td>@quote.Author</td>
                                <td>@quote.Content</td>
                                <td>@quote.CreatedDate.ToShortDateString()</td>
                                <td>
                                    @Html.ActionLink("Edit", "AddEditQuote", "RQPAdmin", new { QuoteId = quote.Id }, new { @class = "btn btn-sm btn-white" })
                                    @Ajax.ActionLink("Delete", "DeleteQuote", "RQPAdmin", new { QuoteId = quote.Id }, new AjaxOptions() { HttpMethod = "POST", OnSuccess = "onDeleted" }, new { @class = "btn-white btn btn-sm btn-delete" })
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>

            }
            else
            {
                <h4 class="no-results">There are no quotes to display.</h4>
            }
        </div>
    </div>
</div>

@section Scripts {
    <script type="text/javascript">
        function onDeleted() {
            window.location.reload();
        }
    </script>    
}

RandomQuotesPlugin/Views/Retail/_RandomQuotesBox.cshtml
@model QuoteModel

@if (Model != null)
{
    <aside class="sidebar">
        <div class="widget cms-widget widget-popular-products">
            <h3><a role="button" data-toggle="collapse" href="#widget-random-quote-box-collapse" aria-expanded="true" aria-controls="widget-random-quote-box-collapse">@ViewBag.Caption</a></h3>
            <div class="collapse in" id="widget-random-quote-box-collapse" aria-expanded="true" role="tabpanel">
                <div class="widget-body">
                    <p>
                        @Model.Content
                    </p>
                    <span>@Model.Author</span>
                    @if (ViewBag.ShowWebsiteLink)
                {
                        <a href="@Model.Website"><i class="fa fa-globe"></i></a>
                    }
                </div>
            </div>
        </div>
    </aside>
}